# https://taskfile.dev

version: '3'

tasks:
  login:
    cmds:
      - dotenvx run -f token -- sh -c 'echo ${TOKEN} | docker login ghcr.io -u totto2727 --password-stdin'

  dev:
    cmds:
      - dotenvx run -f token -- deno run --allow-net --allow-write --allow-env --allow-read="pre-result.json" main.ts

  build:
    cmds:
      - docker build --progress=plain --platform linux/amd64,linux/arm64 -t ghcr.io/totto2727-org/playwright-ja:${TAG} --no-cache .

  push:
    cmds:
      - docker push ghcr.io/totto2727-org/playwright-ja:${TAG}
