name: "Push Image to GHCR"
description: "Push image to GHCR"

inputs:
  username:
    description: "Username"
    required: true
  password:
    description: "Password"
    required: true
  image:
    description: "Image"
    required: true
  tag:
    description: "Tag"
    required: true
  platform:
    description: "Platform"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        tags: |
          ${{ inputs.tag }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ inputs.platform }}
        push: true
        tags: "${{ inputs.image }}:${{ inputs.tag }}"
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          TAG=${{ inputs.tag }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ inputs.image }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
