name: 'Fetch Tag List MCR'
description: 'Fetch image tags in MCR'

inputs:
  image-name:
    description: 'Image name in MCR'
    required: true

outputs:
  arm64:
    description: 'arm64 tag'
    value: ${{ steps.tag-list.outputs.arm64 }}
  amd64:
    description: 'amd64 tag'
    value: ${{ steps.tag-list.outputs.amd64 }}
  multi:
    description: 'multi tag'
    value: ${{ steps.tag-list.outputs.multi }}

runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: "1.44.4"

    - name: List unpushed image tags
      id: tag-list
      shell: bash
      run: deno run --allow-env --allow-write --allow-net main.ts
      env:
        IMAGE_NAME: ${{ inputs.image-name }}

    - shell: bash
      run: |
        echo ${{ steps.tag-list.outputs.arm64 }}
        echo ${{ steps.tag-list.outputs.amd64 }}
        echo ${{ steps.tag-list.outputs.multi }}
