name: Push Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  SOURCE_IMAGE_NAME: playwright
  BUILD_IMAGE_NAME: ghcr.io/totto2727-org/playwright-ja

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag-list:
    name: Fetch tag list
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/fetch-tag-list-mcr
        id: tag-list
        with:
          image-name: ${{ env.SOURCE_IMAGE_NAME }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      arm64: ${{ steps.tag-list.outputs.arm64 }}
      amd64: ${{ steps.tag-list.outputs.amd64 }}
      multi: ${{ steps.tag-list.outputs.multi }}

  push-multi:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest

    needs:
      - tag-list

    permissions:
      packages: write
      attestations: write
      id-token: write
      contents: read

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        tag: ${{fromJson(needs.tag-list.outputs.multi)}}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Push image to GHCR
        uses: ./.github/actions/push-image-ghcr
        with:
          image: ${{ env.BUILD_IMAGE_NAME }}
          tag: ${{ matrix.tag }}
          platform: linux/amd64,linux/arm64
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
